---
title: "COVID Deaths by Race and Sex"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(tidyverse)
library(readr)
library(rvest)
library(httr)
library(lubridate)
library(plotly)
library(viridis)

knitr::opts_chunk$set(
  fig.width = 10,
  fig.asp = .8,
  out.width = "90%", 
  echo = FALSE,
  warning = FALSE
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

```{r}
death_race_age <- GET("https://data.cdc.gov/resource/ks3g-spdg.csv") %>% 
  content("parsed") %>%
  mutate(start_week = ymd(start_week),
         end_week = ymd(end_week))



#combined set
death_race_age_df = 
  death_race_age %>%
  select(state, race_and_hispanic_origin, age_group_new, covid_19_deaths) %>% 
  filter(race_and_hispanic_origin != "Total Deaths",
         state == "United States",
         age_group_new == "18-29 years" |
           age_group_new == "30-49 years" |
           age_group_new == "50-64 years" | 
           age_group_new == "65-74 years" | 
           age_group_new == "75-84 years" | 
           age_group_new == "85 years and over") %>% 
  group_by(race_and_hispanic_origin, age_group_new) %>% 
  summarize(deaths = sum(covid_19_deaths, na.rm = TRUE))

death_age_sex <- GET("https://data.cdc.gov/resource/9bhg-hcku.csv") %>% 
                        content("parsed") %>% mutate(start_date = ymd(start_date), 
                                                      end_date = ymd(end_date))
#combined set
all <- death_age_sex %>% select(start_date, end_date, state,sex,  age_group, covid_19_deaths) %>% 
                         filter(sex == "All Sexes") %>% mutate(start_date = ymd(start_date), 
                                                                end_date = ymd(end_date))



# females only
female <- death_age_sex %>% select(start_date, end_date, state,sex,  age_group, covid_19_deaths) %>% 
                            filter(sex == "Female") %>% mutate(start_date = ymd(start_date), 
                                                                  end_date = ymd(end_date))
# males only 
male <- death_age_sex %>% select(start_date, end_date, state,sex,  age_group, covid_19_deaths) %>% 
                          filter(sex == "Male") %>% mutate(start_date = ymd(start_date), 
                                                            end_date = ymd(end_date))
```

Column {data-width=525}
-----------------------------------------------------------------------

### Graph of deaths by race 

```{r}
covideath <- 
death_race_age_df %>% 
  mutate(age_group = fct_reorder(age_group_new, age_group_new)) %>% 
  rename(`Age Group` = age_group, 
         Deaths = deaths, 
         `Race/origin` = race_and_hispanic_origin) %>% 
  mutate(`Race/origin` = as.factor(`Race/origin`), 
         `Race/origin` = fct_relevel( `Race/origin`, 
                                     levels= c("Unknown", "Non-Hispanic Hative Hawaiian or Other Pacific Islander", "Non-Hispanic More than one race", "Non-Hispanic American Indian or Alaska Native","Non-Hispanic Asian","Non-Hispanic Black","Hispanic", "Non-Hispanic White"))) %>% 
ggplot(aes(x = `Race/origin`, y = Deaths, fill = `Age Group`)) + 
  geom_col(position = "dodge") + 
  labs( title = "COVID-19 Deaths by Race and Hispanic Origin", subtitle = "January 2020 - Novemember 13, 2021") +
  theme(plot.title = element_text(hjust= 1), 
    axis.text.x = element_text(angle = 45), 
    legend.position = "right") + 
  coord_flip() +
  labs(x = "Race and Hispanic Origin",
       y = "COVID-19 Deaths",
       fill = "Age Group")  
ggplotly(covideath)
```


Column {data-width=475}
-----------------------------------------------------------------------

### Graph of deaths by sex 

```{r}
covidage = death_age_sex %>% filter(sex == "Male" | sex == "Female" ) %>% 
                  filter(age_group == "0-17 years"| age_group ==  "18-29 years" |age_group == "30-39 years" 
                         | age_group == "40-49 years" | age_group == "50-64 years"| 
                           age_group ==  "65-74 years"| age_group ==  "75-84 years" | age_group == "85 years and over") %>% 
  mutate(age_group = fct_reorder(age_group, age_group)) %>% 
  ggplot(aes(x = age_group, y = covid_19_deaths, fill= sex)) + 
  geom_col(position = "dodge", stat = "identity") + 
  labs( title = "COVID-19 Deaths by Sex", subtitle = "January 2020 - Novemember 13, 2021") +
  theme(
    axis.text.x = element_text(angle = 90), 
    legend.position = "right", 
    title = element_text(hjust = 0.5)) + 
  xlab("Age Group") + 
  ylab("COVID-19 Deaths") + 
  scale_fill_viridis_d()
ggplotly(covidage)
```


### Graph captions

```{r}
race = "For Non-Hispanic White and Non-Hispanic Asian, the greatest number of people who died from COVID-19 were in the 85+ year age group. In other minority groups, including Hispanic, Non-Hispanic Black, and Non-Hispanic American Indian or Alaska Native, younger age groups had the highest number of COVID-19 deaths, 50-64 years, 65-74 years, and 50-64 years, respectively. These trends could reflect the health disparities that were exacerbated during the pandemic."

sex = "For most of the age groups, there have been more COVID-19 deaths in males compared to females. In the oldest age group (85+ years), more women have died from COVID-19 than men. Studies have suggested that there is an association between COVID-19 outcomes and morbidity by sex. These gender differences could potentially be related to the incidence of COVID-19 comorbidities in men and women. Overall, COVID-19 mortality increases with age and there are sex differences in COVID-19 deaths."

race

sex
```

