---
title: "N.Y.C. COVID-19 Trends Pre- and Post-Vaccine Availability"
output: 
  html_document:
    toc: true
    toc_float: true
    code_folding: hide
---

```{r, message = F}
library(tidyverse)
library(patchwork)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

## Data

```{r, message = F}
#nyc_covid = 
#  read_csv("./us-counties.csv") %>% 
#  filter(county == "New York City") %>% 
#  mutate(day = 1:645,
#         dc_ratio = deaths/cases) %>% 
#  select(-fips) %>% 
#  write_csv("./nyc_covid.csv") Original data set was almost 80 MB in size

nyc_covid = read_csv("./data/nyc_covid.csv")
```

## Death/Case Ratio

```{r}
total_ratio_p = 
  nyc_covid %>% 
  ggplot(aes(x = day, y = dc_ratio)) +
  geom_line() +
  labs(title = "N.Y.C. Death to Cases Ratio from 3/01/20 to 12/05/21",
       x = "Day", y = "Ratio") +
  geom_vline(xintercept = 329, linetype="solid", 
                color = "red", size=0.5)

pre_vacc_ratio_p = 
  nyc_covid %>% 
  slice(1:288) %>% 
  ggplot(aes(x = day, y = dc_ratio)) +
  geom_line() +
  labs(title = "3/01/20 to 12/13/20 (Pre-Vaccine)",
       x = "Day", y = "Ratio") +
  theme(plot.title = element_text(size=10))

post_vacc_ratio_p = 
  nyc_covid %>% 
  slice(289:645) %>% 
  ggplot(aes(x = day, y = dc_ratio)) +
  geom_line() +
  labs(title = "12/14/20 to 12/05/21 (Post-Vaccine)",
       x = "Day", y = "Ratio") +
  theme(plot.title = element_text(size=10))

total_ratio_p / (pre_vacc_ratio_p + post_vacc_ratio_p)
```

## Cases

```{r}
total_nyc_case_lm = 
  lm(cases ~ day, data = nyc_covid) %>% 
  broom::tidy()
total_nyc_case_p = 
  nyc_covid %>% 
  ggplot(aes(x = day, y = cases)) +
  geom_point() +
  geom_smooth(method = "lm", formula = y ~ x) +
  labs(title = "N.Y.C. COVID-19 Cases from 3/01/20 to 12/05/21",
       x = "Day", y = "Cases")

pre_vacc_case_lm = 
  nyc_covid %>% 
  slice(1:328) %>% 
  lm(cases ~ day, data = .) %>% 
  broom::tidy()
pre_vacc_case_p = 
  nyc_covid %>% 
  slice(1:328) %>% 
  ggplot(aes(x = day, y = cases)) +
  geom_point() +
  geom_smooth(method = "lm", formula = y ~ x) +
  labs(title = "3/01/20 to 12/13/20 (Pre-Vaccine)",
       x = "Day", y = "Cases") +
  theme(plot.title = element_text(size=10))

post_vacc_case_lm = 
  nyc_covid %>% 
  slice(329:663) %>% 
  lm(cases ~ day, data = .) %>% 
  broom::tidy()
post_vacc_case_p = 
  nyc_covid %>% 
  slice(329:663) %>%
  ggplot(aes(x = day, y = cases)) +
  geom_point() +
  geom_smooth(method = "lm", formula = y ~ x) +
  labs(title = "12/14/20 to 12/05/21 (Post-Vaccine)",
       x = "Day", y = "Cases") +
  theme(plot.title = element_text(size=10))

total_nyc_case_p / (pre_vacc_case_p + post_vacc_case_p)
```

## Deaths

```{r}
total_nyc_death_lm = 
  lm(deaths ~ day, data = nyc_covid) %>% 
  broom::tidy()
total_nyc_death_p = 
  nyc_covid %>% 
  ggplot(aes(x = day, y = deaths)) +
  geom_point() +
  geom_smooth(method = "lm", formula = y ~ x) +
  labs(title = "N.Y.C. COVID-19 Deaths from 3/01/20 to 12/05/21",
       x = "Day", y = "Deaths")

pre_vacc_death_lm = 
  nyc_covid %>% 
  slice(1:328) %>% 
  lm(deaths ~ day, data = .) %>% 
  broom::tidy()
pre_vacc_death_p = 
  nyc_covid %>% 
  slice(1:328) %>% 
  ggplot(aes(x = day, y = deaths)) +
  geom_point() +
  geom_smooth(method = "lm", formula = y ~ x) +
  labs(title = "3/01/20 to 12/13/20 (Pre-Vaccine)",
       x = "Day", y = "Deaths") +
  theme(plot.title = element_text(size=10))

post_vacc_death_lm = 
  nyc_covid %>% 
  slice(329:663) %>% 
  lm(deaths ~ day, data = .) %>% 
  broom::tidy()
post_vacc_death_p = 
  nyc_covid %>% 
  slice(329:663) %>% 
  ggplot(aes(x = day, y = deaths)) +
  geom_point() +
  geom_smooth(method = "lm", formula = y ~ x) +
  labs(title = "12/14/20 to 12/05/21 (Post-Vaccine)",
       x = "Day", y = "Deaths") +
  theme(plot.title = element_text(size=10))

total_nyc_death_p / (pre_vacc_death_p + post_vacc_death_p)
```

## Slopes

```{r}
tibble(
  metric = c("intercept", "slope"),
  total_case = pull(total_nyc_case_lm, estimate),
  pre_vacc_case = pull(pre_vacc_case_lm, estimate),
  post_vacc_case = pull(post_vacc_case_lm, estimate),
  total_death = pull(total_nyc_death_lm, estimate),
  pre_vacc_death = pull(pre_vacc_death_lm, estimate),
  post_vacc_death = pull(post_vacc_death_lm, estimate)) %>% 
  knitr::kable()

```

N.Y. City Post-vax/Pre-vax Case Ratio: `r post_vacc_case_lm$estimate[2]/pre_vacc_case_lm$estimate[2]` $\\$
N.Y. City Post-vax/Pre-vax Death Ratio: `r post_vacc_death_lm$estimate[2]/pre_vacc_death_lm$estimate[2]`