---
title: "Report"
output: 
  html_document:
    toc: true
    toc_float: true
    code_folding: hide
---

```{r setup, include=FALSE}
library(tidyverse)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

## Methods 
expand (Heidi)

## Data Sources

- [NY Times COVID-19 data set](https://github.com/nytimes/covid-19-data/)
- [Our World COVID-19 data](https://github.com/owid/covid-19-data/tree/master/public/data/vaccinations)
- [CDC's United States COVID-19 Cases and Deaths by State Over Time](https://data.cdc.gov/Case-Surveillance/United-States-COVID-19-Cases-and-Deaths-by-State-o/9mfq-cb36)
- CDC's COVID-19 deaths by: [Sex and age](https://data.cdc.gov/NCHS/Provisional-COVID-19-Deaths-by-Sex-and-Age/9bhg-hcku), [Race and Hispanic origin](https://data.cdc.gov/NCHS/Provisional-COVID-19-Deaths-Distribution-of-Deaths/pj7m-y5uh), [Week and Urbanicity](https://data.cdc.gov/NCHS/Provisional-COVID-19-Deaths-by-Week-and-Urbanicity/hkhc-f7hg), [Educational Attainment](https://data.cdc.gov/NCHS/AH-Provisional-COVID-19-Deaths-by-Race-and-Educati/i6ej-9eac)
- [CDC's Vaccine hesitancy for COVID-19: county and local estimates](https://data.cdc.gov/Vaccinations/Vaccine-Hesitancy-for-COVID-19-County-and-local-es/q9mh-h2tw)
- CDC's COVID-19 Vaccine Distribution Allocations by Jurisdiction - [Pfizer](https://data.cdc.gov/Vaccinations/COVID-19-Vaccine-Distribution-Allocations-by-Juris/saz5-9hgg), [Moderna](https://data.cdc.gov/Vaccinations/COVID-19-Vaccine-Distribution-Allocations-by-Juris/b7pe-5nws), [J&J](https://data.cdc.gov/Vaccinations/COVID-19-Vaccine-Distribution-Allocations-by-Juris/w9zu-fywh)
- [CDC's COVID-19 vaccinations in the United States, County](https://data.cdc.gov/Vaccinations/COVID-19-Vaccinations-in-the-United-States-County/8xkx-amqh)

## Research Questions

How do trends in cases and deaths compare in the U.S. and NYC (and globally) from January 2020 to November 2021?

How has the vaccine been distributed in these areas? What are the rates of uptake/vaccination?

What are the differences in COVID-19 deaths by different subgroups (age, sex, race, etc.)? Are these differences statistically significant?

What are the trends in mask usage, disease rates, and vaccine rates and how are they related to one another or isolated by region?

What are trends in vaccination, vaccine hesitancy, and allocation of vaccine type and how do they compare across NYC and the United States?

How did the release of vaccines affect the case and death rates in NYC and across the country? Did they have an effect? What about in areas with low vs high vaccination rates?

How do the seasonal/quarterly rates of COVID-19 infection differ and are they significantly different for the same seasons/quarters pre- and post-vaccine availability?

## Results (links to other pages)

- [Covid case and death rates](covid_deaths.html) --> Louis and Alex
--> Include race and gender data here
--> Covid case rates and death rates (including US cases vs. death figure)
--> Shows how case rate and death rate changed after vaccination

- [Vaccination rates](vaccination_rates.html) --> Philip
--> Line graphs of vaccination by different subgroups
--> Map vaccination rates by state over time
--> Map of vaccination uptake rate over time

- [Vaccine hesitancy](vaccine_hesitancy.html) --> Kaila and Heidi
--> Overall hesitancy
--> Maps of percent hesitancy by state
--> Explore how social vulnerability index may impact this
    Map of SVI
    Boxplots
    Statistical analysis

## Discussion



